version: "3"
services:
  php:
    container_name: "Trabalho2a"
    image: php:8.1.16-apache
    volumes:
      - ./site/:/var/www/html/
    ports:
      - 8080:80
  db:
   image: mariadb:10.5
   container_name: "mariadb_projeto1-2b"
   restart: always
   environment:
     - MARIADB_USER=root
     - MARIADB_ROOT_PASSWORD=123
  adminer:
   image: adminer:4.8.1
   container_name: "adminer_projeto1-2b"
   restart: always
   ports:
     - 85:8080
